[package]
name = "git-snow"
dependencies = "Snow fall in your terminal"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = ["events"] }
fastrand = "2.3.0"
